-- Supabase schema for Firstcry imports
-- Run this in the Supabase SQL editor to create tables expected by the importer

-- Sales
CREATE TABLE IF NOT EXISTS public.firstcry_sales (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poid text,
  order_date timestamp with time zone,
  product_id integer,
  brand_name text,
  business_type text,
  quantity numeric,
  mrp numeric,
  mrp_sales numeric,
  subcategory_name text,
  category_name text,
  stock_type text,
  vendor_style_code text,
  source_file text,
  sheet_name text,
  inserted_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_firstcry_sales_product_id ON public.firstcry_sales(product_id);
CREATE INDEX IF NOT EXISTS idx_firstcry_sales_source_file ON public.firstcry_sales(source_file);

-- GST reconciliation
CREATE TABLE IF NOT EXISTS public.firstcry_gst_reconciliation (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_name text,
  state text,
  gstr_type text,
  credit_type text,
  financial_year text,
  transaction_month text,
  return_frequency text,
  gstin text,
  reference_id text,
  invoice_no text,
  invoice_date timestamptz,
  cgst numeric,
  sgst numeric,
  igst numeric,
  gst_type text,
  total_tax numeric,
  created_by text,
  status text,
  exp_id text,
  source_file text,
  sheet_name text,
  inserted_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_firstcry_gst_invoice_no ON public.firstcry_gst_reconciliation(invoice_no);
CREATE INDEX IF NOT EXISTS idx_firstcry_gst_source_file ON public.firstcry_gst_reconciliation(source_file);

-- Product box details
CREATE TABLE IF NOT EXISTS public.firstcry_product_box_details (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sr_no integer,
  product_id integer,
  vendor_style_code text,
  product_name text,
  packaging_id integer,
  length_cm numeric,
  breadth_cm numeric,
  height_cm numeric,
  weight_kg numeric,
  multiple_packaging_required text,
  source_file text,
  sheet_name text,
  inserted_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_firstcry_box_product_id ON public.firstcry_product_box_details(product_id);

-- Sale returns
CREATE TABLE IF NOT EXISTS public.firstcry_sale_returns (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sr_no integer,
  order_date timestamptz,
  sales_return_date timestamptz,
  poid text,
  product_id integer,
  product_name text,
  brand_names text,
  mrp numeric,
  ordered_quantity numeric,
  quantity numeric,
  rpid_awb text,
  reason text,
  subtype_reason text,
  subreason text,
  vendor_style_code text,
  source_file text,
  sheet_name text,
  inserted_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_firstcry_sale_returns_product_id ON public.firstcry_sale_returns(product_id);

-- Vendor invoices
CREATE TABLE IF NOT EXISTS public.firstcry_vendor_invoices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fc_reference_no text,
  invoice_no text,
  invoice_date timestamptz,
  stock_type text,
  site_type text,
  invoice_status text,
  vendor_name text,
  vendor_gst_no text,
  invoice_quantity numeric,
  gross_amount numeric,
  tax_amount numeric,
  net_amount numeric,
  reject_reason text,
  company_name text,
  source_file text,
  sheet_name text,
  inserted_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_firstcry_vendor_invoices_invoice_no ON public.firstcry_vendor_invoices(invoice_no);

-- Vendor reconciliation
CREATE TABLE IF NOT EXISTS public.firstcry_vendor_reconciliation (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sr_no integer,
  fc_ref_no text,
  order_ids text,
  order_date timestamptz,
  shipping_date timestamptz,
  delivery_date timestamptz,
  sr_rto_date timestamptz,
  product_id integer,
  hsn_code text,
  qty numeric,
  mrp numeric,
  base_cost numeric,
  gross_amount numeric,
  cgst_percent numeric,
  cgst_amount numeric,
  sgst_percent numeric,
  sgst_amount numeric,
  total numeric,
  vendor_invoice_no text,
  payment_advice_no text,
  debit_note_no text,
  whpoid text,
  vendor_style_code text,
  awb_no text,
  sr_qty numeric,
  sr_total_amount numeric,
  sr_gross_amount numeric,
  rto_qty numeric,
  rto_total_amount numeric,
  rto_gross_amount numeric,
  source_file text,
  sheet_name text,
  inserted_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_firstcry_vendor_recon_product_id ON public.firstcry_vendor_reconciliation(product_id);

-- Payment advice (flexible)
CREATE TABLE IF NOT EXISTS public.firstcry_payment_advice (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tds_amount numeric,
  other_columns jsonb,
  source_file text,
  sheet_name text,
  inserted_at timestamptz DEFAULT now()
);

-- Debit notes / pre-post delivery docs
CREATE TABLE IF NOT EXISTS public.firstcry_debit_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  note_type text,
  company text,
  batch_id text,
  generation_date timestamptz,
  raw_text text,
  source_file text,
  sheet_name text,
  inserted_at timestamptz DEFAULT now()
);

-- Raw fallback table
CREATE TABLE IF NOT EXISTS public.firstcry_raw_files (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filename text,
  sheet_name text,
  row_index integer,
  row_data jsonb,
  source_file text,
  inserted_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_firstcry_raw_filename ON public.firstcry_raw_files(filename);

-- Helpful FK-free indexes for quick queries
CREATE INDEX IF NOT EXISTS idx_firstcry_all_source_file ON public.firstcry_raw_files(source_file);

-- End of schema
