#!/usr/bin/env node
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY;

if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) {
  throw new Error('Missing SUPABASE_URL or SUPABASE_SERVICE_KEY');
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

async function createAdminUser() {
  const email = process.env.ADMIN_EMAIL;
  const password = process.env.ADMIN_PASSWORD;
  const name = process.env.ADMIN_NAME || 'Admin User';

  if (!email || !password) {
    throw new Error('Missing ADMIN_EMAIL or ADMIN_PASSWORD');
  }

  console.log('Creating admin user in Supabase Auth...\n');

  try {
    // Create user via Auth Admin API
    const { data: authData, error: authError } = await supabase.auth.admin.createUser({
      email,
      password,
      email_confirm: true,
      user_metadata: { name }
    });

    if (authError) {
      if (authError.message.includes('already registered')) {
        console.log('⚠️  User already exists in auth');
        console.log(`Email: ${email}`);
        console.log('Password sourced from ADMIN_PASSWORD');
        return;
      }
      console.error('❌ Auth error:', authError.message);
      return;
    }

    if (!authData.user) {
      console.error('❌ No user returned');
      return;
    }

    const userId = authData.user.id;
    console.log('✅ User created in Auth:', userId);

    // Create user_roles entry for admin role
    const { error: roleError } = await supabase
      .from('user_roles')
      .insert([
        {
          user_id: userId,
          role: 'admin'
        }
      ]);

    if (roleError) {
      console.log('⚠️  Could not set admin role (table may not exist)');
      console.log('Create this table in Supabase SQL editor:\n');
      console.log(`CREATE TABLE IF NOT EXISTS public.user_roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role text NOT NULL,
  created_at timestamptz DEFAULT now()
);
CREATE INDEX idx_user_roles_user_id ON user_roles(user_id);
INSERT INTO user_roles (user_id, role) VALUES ('${userId}', 'admin');`);
    } else {
      console.log('✅ Admin role assigned');
    }

    console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('✅ ADMIN USER CREATED');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log(`📧 Email:    ${email}`);
    console.log('🔐 Password sourced from ADMIN_PASSWORD');
    console.log(`👤 User ID:  ${userId}`);
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

  } catch (error) {
    console.error('Error:', error);
  }
}

createAdminUser();
