
ALTER TABLE public.leads
ADD COLUMN IF NOT EXISTS website text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS gstin text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS whatsapp text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS address text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS city text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS state text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS imported_via text DEFAULT NULL;
